version: '3.3'

services:
  app:
    build: .
    container_name: oscar-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www/src
      - ./tests/:/var/www/tests
      - ./public/:/var/www/public
      - ./phpunit.xml:/var/www/phpunit.xml
      - ./coverage/:/var/www/coverage:delegated
    networks:
      - oscar-network
  nginx:
    image: nginx:1.19-alpine
    container_name: oscar-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/src
      - ./public/:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - oscar-network
  db:
    container_name: oscar-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - oscar-network
  coverage:
    image: nginx:1.19-alpine
    container_name: oscar-coverage
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./coverage/:/usr/share/nginx/html
networks:
    oscar-network:
        driver: bridge